//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AvisoLegalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AvisoLegalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Legal.Resources.AvisoLegalResource", typeof(AvisoLegalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollo y explotación de software para la automatización de operaciones en mercados de criptomonedas.
        /// </summary>
        internal static string ActivityValue {
            get {
                return ResourceManager.GetString("ActivityValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad.
        /// </summary>
        internal static string LabelActivity {
            get {
                return ResourceManager.GetString("LabelActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicilio.
        /// </summary>
        internal static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        internal static string LabelContact {
            get {
                return ResourceManager.GetString("LabelContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIF.
        /// </summary>
        internal static string LabelNIF {
            get {
                return ResourceManager.GetString("LabelNIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titular.
        /// </summary>
        internal static string LabelOwner {
            get {
                return ResourceManager.GetString("LabelOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma:.
        /// </summary>
        internal static string LangLabel {
            get {
                return ResourceManager.GetString("LangLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizado: 4 de junio de 2026.
        /// </summary>
        internal static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso Legal | Sergi Ortiz Gómez.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En cumplimiento del artículo 10 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y del Comercio Electrónico (LSSI-CE), se facilitan los siguientes datos identificativos:.
        /// </summary>
        internal static string Section1Intro {
            get {
                return ResourceManager.GetString("Section1Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Identificación del Titular (LSSI, art. 10).
        /// </summary>
        internal static string Section1Title {
            get {
                return ResourceManager.GetString("Section1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El titular ofrece servicios de software de trading automatizado de criptomonedas, incluyendo herramientas de configuración de estrategias, análisis de mercado y gestión de comisiones, prestados íntegramente desde España a través de plataformas digitales. Estos servicios no constituyen asesoramiento financiero ni de inversión, y no implican la gestión, custodia ni transferencia directa de fondos del usuario..
        /// </summary>
        internal static string Section2Text {
            get {
                return ResourceManager.GetString("Section2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Objeto y Servicios.
        /// </summary>
        internal static string Section2Title {
            get {
                return ResourceManager.GetString("Section2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los contenidos de los sitios web del titular —incluyendo textos, diseños, código fuente, logotipos e imágenes— son propiedad de Sergi Ortiz Gómez o cuentan con la correspondiente licencia de uso. Queda prohibida su reproducción, distribución, transformación o comunicación pública sin autorización expresa y por escrito del titular..
        /// </summary>
        internal static string Section3Text {
            get {
                return ResourceManager.GetString("Section3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Propiedad Intelectual e Industrial.
        /// </summary>
        internal static string Section3Title {
            get {
                return ResourceManager.GetString("Section3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El software de trading opera según los ajustes configurados por el propio usuario. El titular no garantiza rentabilidad ni resultado alguno de las operaciones ejecutadas. No se asume responsabilidad por pérdidas derivadas de la configuración incorrecta de estrategias, fallos técnicos de exchanges externos, interrupciones de conectividad o cualquier otra circunstancia ajena al control del prestador..
        /// </summary>
        internal static string Section4Text {
            get {
                return ResourceManager.GetString("Section4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Limitación de Responsabilidad.
        /// </summary>
        internal static string Section4Title {
            get {
                return ResourceManager.GetString("Section4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El presente Aviso Legal se rige por la legislación española. Para la resolución de cualquier controversia derivada del acceso o uso de los servicios del titular, las partes se someten, con renuncia expresa a cualquier otro fuero, a los Juzgados y Tribunales del domicilio del usuario o, a elección del prestador, a los de Las Palmas de Gran Canaria, España..
        /// </summary>
        internal static string Section5Text {
            get {
                return ResourceManager.GetString("Section5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Ley Aplicable y Jurisdicción.
        /// </summary>
        internal static string Section5Title {
            get {
                return ResourceManager.GetString("Section5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso Legal.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
